apiVersion: v1
kind: Service
metadata:
  name: bright-app
  namespace: bright
spec:
  selector:
    app: bright-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort