server:
  port: 8171
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: localSQLUser
    password: password
    url: jdbc:mysql://localhost:3306/electiondb
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8161/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"