server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://employee-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: idea-service
        uri: lb://election-service
        predicates:
        - Path=/idea/**
        filters:
        - RewritePath=/idea/(?<path>.*), /$\{path}
      - id: election-service
        uri: lb://election-service
        predicates:
        - Path=/election/**
        filters:
        - RewritePath=/election/(?<path>.*), /$\{path}