server:
  port: 8160

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8161/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
     gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
          cors-configurations:
             '[/**]':
               allowed-origins: "http://localhost:4200"
               allowed-methods: "*"
               allowed-headers: "*"
               allow-credentials: true
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: auth-service
        uri: lb://user-service
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
      - id: election-service
        uri: lb://election-service
        predicates:
        - Path=/election/**
        filters:
        - RewritePath=/election/(?<path>.*), /$\{path}
      - id: idea-service
        uri: lb://idea-service
        predicates:
        - Path=/idea/**
        filters:
        - RewritePath=/idea/(?<path>.*), /$\{path}