server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    idea:
      path: /idea/**
      serviceId: idea-service
    user:
      path: /user/**
      serviceId: user-service
    election:
      path: /election/**
      serviceId: election-service